### ISSUE TITLE
Unsupported parameter "masked" in Ansible service module (6.2.1.2 | PATCH | Ensure auditd service is enabled and active)

### ISSUE THREAD

**Issue by VitaliySynytskyi** [ansible-lockdown/UBUNTU24-CIS#12]
**Describe the Issue**

The task "6.2.1.2 | PATCH | Ensure auditd service is enabled and active" in cis_6.2.1.x.yml is failing due to the use of an unsupported parameter masked in the Ansible service module.

**Error message:**
```
TASK [ansible-lockdown.UBUNTU24-CIS : 6.2.1.2 | PATCH | Ensure auditd service is enabled and active] ***
fatal: [instance]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.service) module: masked. Supported parameters include: arguments, enabled, name, pattern, runlevel, sleep, state (args)."}
```

**Expected Behavior**

The auditd service should be enabled and started without any errors.

**Actual Behavior**

The Ansible task fails due to the masked parameter being unsupported in the service module.
The service module does not support masked, but the systemd module does.

**Control(s) Affected**

6.2.1.2 – Ensure auditd service is enabled and active.

**Environment:**

    Branch being used: devel
    Ansible Version: 2.18.2
    Host Python Version: 3.11.11
    Ansible Server Python Version: 3.12.3
    Additional Details: Running on Ubuntu 24.04

**Possible Solution 1**

Remove the masked parameter from the service module, as it is not supported:
```
- name: "6.2.1.2 | PATCH | Ensure auditd service is enabled and active"
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true
```

**Possible Solution 2**

Replace the service module with the systemd module to properly handle masking:
```
- name: "6.2.1.2 | PATCH | Ensure auditd service is enabled and active"
  ansible.builtin.systemd:
    name: auditd
    enabled: true
    state: started
    masked: false  # Ensures the service is unmasked before enabling
```
